export interface TtsVoiceOption {
  id: string
  name: string
  description: string
  sampleText: string
  sampleAudioUrl: string
  provider: 'edge'
  languageCode: string
  gender?: 'female' | 'male' | 'neutral'
  accent?: string
  toneTags?: string[]
  characterArchetype?: string
  paletteKey?: 'violet' | 'cyan' | 'amber' | 'rose' | 'emerald'
}

export type VoiceLibraryProviderId = 'sarvam' | 'elevenlabs' | 'openai' | 'other'

export interface VoiceLibraryProviderStatus {
  id: VoiceLibraryProviderId
  name: string
  status: 'configured' | 'not_set'
  description: string
}

export const TTS_VOICE_OPTIONS: TtsVoiceOption[] = [
  {
    id: 'en-US-JennyNeural',
    name: 'Jenny (US)',
    description: 'Natural US English, female',
    sampleText: 'Did you know Sudar can personalize your learning path based on how you study best?',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'en-US',
    gender: 'female',
    accent: 'US English',
    toneTags: ['Natural', 'Supportive'],
    characterArchetype: 'Guide',
    paletteKey: 'violet',
  },
  {
    id: 'en-US-AriaNeural',
    name: 'Aria (US)',
    description: 'Confident US English, female',
    sampleText: 'Sudar is designed to make every lesson feel like it was built just for you.',
    sampleAudioUrl: '/audio/voice-previews/en-US-AriaNeural.mp3',
    provider: 'edge',
    languageCode: 'en-US',
    gender: 'female',
    accent: 'US English',
    toneTags: ['Confident', 'Clear'],
    characterArchetype: 'Host',
    paletteKey: 'rose',
  },
  {
    id: 'en-US-AnaNeural',
    name: 'Ana (US)',
    description: 'Warm US English, female',
    sampleText: 'With Sudar, your courses adapt in real time so learning stays clear and engaging.',
    sampleAudioUrl: '/audio/voice-previews/en-US-AnaNeural.mp3',
    provider: 'edge',
    languageCode: 'en-US',
    gender: 'female',
    accent: 'US English',
    toneTags: ['Warm', 'Friendly'],
    characterArchetype: 'Mentor',
    paletteKey: 'amber',
  },
  {
    id: 'en-US-GuyNeural',
    name: 'Guy (US)',
    description: 'Natural US English, male',
    sampleText: 'Sudar helps you move from confusion to confidence with guided, adaptive support.',
    sampleAudioUrl: '/audio/voice-previews/en-US-GuyNeural.mp3',
    provider: 'edge',
    languageCode: 'en-US',
    gender: 'male',
    accent: 'US English',
    toneTags: ['Natural', 'Steady'],
    characterArchetype: 'Coach',
    paletteKey: 'cyan',
  },
  {
    id: 'en-US-ChristopherNeural',
    name: 'Christopher (US)',
    description: 'Expressive US English, male',
    sampleText: 'Sudar combines AI tutoring, progress insights, and modality switching in one platform.',
    sampleAudioUrl: '/audio/voice-previews/en-US-ChristopherNeural.mp3',
    provider: 'edge',
    languageCode: 'en-US',
    gender: 'male',
    accent: 'US English',
    toneTags: ['Expressive', 'Bold'],
    characterArchetype: 'Storyteller',
    paletteKey: 'emerald',
  },
  {
    id: 'en-GB-SoniaNeural',
    name: 'Sonia (UK)',
    description: 'Natural British English, female',
    sampleText: 'Sudar can recommend what to learn next using your pace, progress, and preferences.',
    sampleAudioUrl: '/audio/voice-previews/en-GB-SoniaNeural.mp3',
    provider: 'edge',
    languageCode: 'en-GB',
    gender: 'female',
    accent: 'British English',
    toneTags: ['Natural', 'Calm'],
    characterArchetype: 'Narrator',
    paletteKey: 'violet',
  },
  {
    id: 'en-GB-LibbyNeural',
    name: 'Libby (UK)',
    description: 'Clear British English, female',
    sampleText: 'Learn with Sudar in text, audio, video, and more, while your learner profile keeps improving.',
    sampleAudioUrl: '/audio/voice-previews/en-GB-LibbyNeural.mp3',
    provider: 'edge',
    languageCode: 'en-GB',
    gender: 'female',
    accent: 'British English',
    toneTags: ['Clear', 'Composed'],
    characterArchetype: 'Presenter',
    paletteKey: 'cyan',
  },
  {
    id: 'en-GB-RyanNeural',
    name: 'Ryan (UK)',
    description: 'Natural British English, male',
    sampleText: 'Sudar gives every learner a personal, non-judgmental tutor experience.',
    sampleAudioUrl: '/audio/voice-previews/en-GB-RyanNeural.mp3',
    provider: 'edge',
    languageCode: 'en-GB',
    gender: 'male',
    accent: 'British English',
    toneTags: ['Natural', 'Balanced'],
    characterArchetype: 'Companion',
    paletteKey: 'amber',
  },
  {
    id: 'en-IN-NeerjaNeural',
    name: 'Neerja (India)',
    description: 'Indian English, female',
    sampleText: 'Sudar is built to support diverse learners with adaptive, personalized learning journeys.',
    sampleAudioUrl: '/audio/voice-previews/en-IN-NeerjaNeural.mp3',
    provider: 'edge',
    languageCode: 'en-IN',
    gender: 'female',
    accent: 'Indian English',
    toneTags: ['Grounded', 'Warm'],
    characterArchetype: 'Teacher',
    paletteKey: 'rose',
  },
  {
    id: 'india_shreya',
    name: 'Shreya (India)',
    description: 'Indian English, expressive',
    sampleText: 'Did you know Sudar can turn one course into multiple learning modalities for better outcomes?',
    sampleAudioUrl: '/audio/voice-previews/india_shreya.mp3',
    provider: 'edge',
    languageCode: 'en-IN',
    gender: 'female',
    accent: 'Indian English',
    toneTags: ['Expressive', 'Dynamic'],
    characterArchetype: 'Performer',
    paletteKey: 'emerald',
  },
  {
    id: 'india_shubh',
    name: 'Shubh (India)',
    description: 'Indian English, conversational',
    sampleText: 'Sudar is designed to learn with you, for you, every time you come back to study.',
    sampleAudioUrl: '/audio/voice-previews/india_shubh.mp3',
    provider: 'edge',
    languageCode: 'en-IN',
    gender: 'male',
    accent: 'Indian English',
    toneTags: ['Conversational', 'Relaxed'],
    characterArchetype: 'Friend',
    paletteKey: 'violet',
  },
  {
    id: 'en-AU-NatashaNeural',
    name: 'Natasha (Australia)',
    description: 'Australian English, female',
    sampleText: 'Sudar helps you learn faster by adapting lessons to how you engage.',
    sampleAudioUrl: '/audio/voice-previews/en-AU-NatashaNeural.mp3',
    provider: 'edge',
    languageCode: 'en-AU',
    gender: 'female',
    accent: 'Australian English',
    toneTags: ['Bright', 'Clear'],
    characterArchetype: 'Facilitator',
    paletteKey: 'cyan',
  },
  {
    id: 'en-CA-ClaraNeural',
    name: 'Clara (Canada)',
    description: 'Canadian English, female',
    sampleText: 'Sudar keeps your learning journey personalized across every modality.',
    sampleAudioUrl: '/audio/voice-previews/en-CA-ClaraNeural.mp3',
    provider: 'edge',
    languageCode: 'en-CA',
    gender: 'female',
    accent: 'Canadian English',
    toneTags: ['Balanced', 'Friendly'],
    characterArchetype: 'Advisor',
    paletteKey: 'amber',
  },
  {
    id: 'hi-IN-SwaraNeural',
    name: 'Swara (Hindi)',
    description: 'Hindi, female',
    sampleText: 'Sudar aapke learning style ke hisaab se content ko personalize karta hai.',
    sampleAudioUrl: '/audio/voice-previews/hi-IN-SwaraNeural.mp3',
    provider: 'edge',
    languageCode: 'hi-IN',
    gender: 'female',
    accent: 'Hindi',
    toneTags: ['Warm', 'Assured'],
    characterArchetype: 'Teacher',
    paletteKey: 'rose',
  },
  {
    id: 'es-ES-ElviraNeural',
    name: 'Elvira (Spanish)',
    description: 'Spanish, female',
    sampleText: 'Sudar adapta cada curso para mejorar tu progreso de aprendizaje.',
    sampleAudioUrl: '/audio/voice-previews/es-ES-ElviraNeural.mp3',
    provider: 'edge',
    languageCode: 'es-ES',
    gender: 'female',
    accent: 'Spanish',
    toneTags: ['Energetic', 'Clear'],
    characterArchetype: 'Presenter',
    paletteKey: 'emerald',
  },
  {
    id: 'fr-FR-DeniseNeural',
    name: 'Denise (French)',
    description: 'French, female',
    sampleText: 'Sudar adapte vos cours selon votre rythme et vos preferences.',
    sampleAudioUrl: '/audio/voice-previews/fr-FR-DeniseNeural.mp3',
    provider: 'edge',
    languageCode: 'fr-FR',
    gender: 'female',
    accent: 'French',
    toneTags: ['Smooth', 'Poised'],
    characterArchetype: 'Narrator',
    paletteKey: 'violet',
  },
  {
    id: 'de-DE-KatjaNeural',
    name: 'Katja (German)',
    description: 'German, female',
    sampleText: 'Sudar passt Inhalte an, damit Lernen klarer und effektiver wird.',
    sampleAudioUrl: '/audio/voice-previews/de-DE-KatjaNeural.mp3',
    provider: 'edge',
    languageCode: 'de-DE',
    gender: 'female',
    accent: 'German',
    toneTags: ['Direct', 'Calm'],
    characterArchetype: 'Coach',
    paletteKey: 'cyan',
  },
  {
    id: 'ja-JP-NanamiNeural',
    name: 'Nanami (Japanese)',
    description: 'Japanese, female',
    sampleText: 'Sudar wa anata no manabikata ni awasete content o saitekika shimasu.',
    sampleAudioUrl: '/audio/voice-previews/ja-JP-NanamiNeural.mp3',
    provider: 'edge',
    languageCode: 'ja-JP',
    gender: 'female',
    accent: 'Japanese',
    toneTags: ['Gentle', 'Focused'],
    characterArchetype: 'Guide',
    paletteKey: 'amber',
  },
  {
    id: 'pt-BR-FranciscaNeural',
    name: 'Francisca (Brazil)',
    description: 'Portuguese (Brazil), female',
    sampleText: 'Sudar personaliza suas aulas para acelerar seu aprendizado.',
    sampleAudioUrl: '/audio/voice-previews/pt-BR-FranciscaNeural.mp3',
    provider: 'edge',
    languageCode: 'pt-BR',
    gender: 'female',
    accent: 'Brazilian Portuguese',
    toneTags: ['Friendly', 'Confident'],
    characterArchetype: 'Mentor',
    paletteKey: 'rose',
  },
]

export const TTS_VOICE_OPTIONS_BY_ID = Object.fromEntries(
  TTS_VOICE_OPTIONS.map((voice) => [voice.id, voice])
) as Record<string, TtsVoiceOption>

export const TTS_VOICE_ID_ALIASES: Record<string, string> = {
  sarvam_shreya: 'india_shreya',
  sarvam_shubh: 'india_shubh',
}

export function normalizeTtsVoiceId(voiceId: string | null | undefined): string | null {
  if (!voiceId) return null
  return TTS_VOICE_ID_ALIASES[voiceId] ?? voiceId
}
