export interface TtsVoiceOption {
  id: string
  name: string
  description: string
  sampleText: string
  sampleAudioUrl: string
  provider: 'edge' | 'sarvam'
  languageCode: string
  gender?: 'female' | 'male' | 'neutral'
  accent?: string
  toneTags?: string[]
  characterArchetype?: string
  paletteKey?: 'violet' | 'cyan' | 'amber' | 'rose' | 'emerald'
}

export type VoiceLibraryProviderId = 'sarvam' | 'elevenlabs' | 'openai' | 'other'

export interface VoiceLibraryProviderStatus {
  id: VoiceLibraryProviderId
  name: string
  status: 'configured' | 'not_set'
  description: string
}

export const TTS_VOICE_OPTIONS: TtsVoiceOption[] = [
  {
    id: 'en-US-JennyNeural',
    name: 'Jenny (US)',
    description: 'Natural US English, female',
    sampleText: 'Did you know Sudar can personalize your learning path based on how you study best?',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'en-US',
    gender: 'female',
    accent: 'US English',
    toneTags: ['Natural', 'Supportive'],
    characterArchetype: 'Guide',
    paletteKey: 'violet',
  },
  {
    id: 'en-US-AriaNeural',
    name: 'Aria (US)',
    description: 'Confident US English, female',
    sampleText: 'Sudar is designed to make every lesson feel like it was built just for you.',
    sampleAudioUrl: '/audio/voice-previews/en-US-AriaNeural.mp3',
    provider: 'edge',
    languageCode: 'en-US',
    gender: 'female',
    accent: 'US English',
    toneTags: ['Confident', 'Clear'],
    characterArchetype: 'Host',
    paletteKey: 'rose',
  },
  {
    id: 'en-US-AnaNeural',
    name: 'Ana (US)',
    description: 'Warm US English, female',
    sampleText: 'With Sudar, your courses adapt in real time so learning stays clear and engaging.',
    sampleAudioUrl: '/audio/voice-previews/en-US-AnaNeural.mp3',
    provider: 'edge',
    languageCode: 'en-US',
    gender: 'female',
    accent: 'US English',
    toneTags: ['Warm', 'Friendly'],
    characterArchetype: 'Mentor',
    paletteKey: 'amber',
  },
  {
    id: 'en-US-GuyNeural',
    name: 'Guy (US)',
    description: 'Natural US English, male',
    sampleText: 'Sudar helps you move from confusion to confidence with guided, adaptive support.',
    sampleAudioUrl: '/audio/voice-previews/en-US-GuyNeural.mp3',
    provider: 'edge',
    languageCode: 'en-US',
    gender: 'male',
    accent: 'US English',
    toneTags: ['Natural', 'Steady'],
    characterArchetype: 'Coach',
    paletteKey: 'cyan',
  },
  {
    id: 'en-US-ChristopherNeural',
    name: 'Christopher (US)',
    description: 'Expressive US English, male',
    sampleText: 'Sudar combines AI tutoring, progress insights, and modality switching in one platform.',
    sampleAudioUrl: '/audio/voice-previews/en-US-ChristopherNeural.mp3',
    provider: 'edge',
    languageCode: 'en-US',
    gender: 'male',
    accent: 'US English',
    toneTags: ['Expressive', 'Bold'],
    characterArchetype: 'Storyteller',
    paletteKey: 'emerald',
  },
  {
    id: 'en-GB-SoniaNeural',
    name: 'Sonia (UK)',
    description: 'Natural British English, female',
    sampleText: 'Sudar can recommend what to learn next using your pace, progress, and preferences.',
    sampleAudioUrl: '/audio/voice-previews/en-GB-SoniaNeural.mp3',
    provider: 'edge',
    languageCode: 'en-GB',
    gender: 'female',
    accent: 'British English',
    toneTags: ['Natural', 'Calm'],
    characterArchetype: 'Narrator',
    paletteKey: 'violet',
  },
  {
    id: 'en-GB-LibbyNeural',
    name: 'Libby (UK)',
    description: 'Clear British English, female',
    sampleText: 'Learn with Sudar in text, audio, video, and more, while your learner profile keeps improving.',
    sampleAudioUrl: '/audio/voice-previews/en-GB-LibbyNeural.mp3',
    provider: 'edge',
    languageCode: 'en-GB',
    gender: 'female',
    accent: 'British English',
    toneTags: ['Clear', 'Composed'],
    characterArchetype: 'Presenter',
    paletteKey: 'cyan',
  },
  {
    id: 'en-GB-RyanNeural',
    name: 'Ryan (UK)',
    description: 'Natural British English, male',
    sampleText: 'Sudar gives every learner a personal, non-judgmental tutor experience.',
    sampleAudioUrl: '/audio/voice-previews/en-GB-RyanNeural.mp3',
    provider: 'edge',
    languageCode: 'en-GB',
    gender: 'male',
    accent: 'British English',
    toneTags: ['Natural', 'Balanced'],
    characterArchetype: 'Companion',
    paletteKey: 'amber',
  },
  {
    id: 'en-IN-NeerjaNeural',
    name: 'Neerja (India)',
    description: 'Indian English, female',
    sampleText: 'Sudar is built to support diverse learners with adaptive, personalized learning journeys.',
    sampleAudioUrl: '/audio/voice-previews/en-IN-NeerjaNeural.mp3',
    provider: 'edge',
    languageCode: 'en-IN',
    gender: 'female',
    accent: 'Indian English',
    toneTags: ['Grounded', 'Warm'],
    characterArchetype: 'Teacher',
    paletteKey: 'rose',
  },
  {
    id: 'en-IN-PrabhatNeural',
    name: 'Prabhat (India)',
    description: 'Indian English, male',
    sampleText: 'Sudar is designed to learn with you, for you, every time you come back to study.',
    sampleAudioUrl: '/audio/voice-previews/en-IN-PrabhatNeural.mp3',
    provider: 'edge',
    languageCode: 'en-IN',
    gender: 'male',
    accent: 'Indian English',
    toneTags: ['Conversational', 'Relaxed'],
    characterArchetype: 'Friend',
    paletteKey: 'violet',
  },
  {
    id: 'sarvam_shreya',
    name: 'Shreya (Sarvam)',
    description: 'Indian English / Indian languages via Sarvam (requires Intelligence SARVAM_API_KEY)',
    sampleText: 'Did you know Sudar can turn one course into multiple learning modalities for better outcomes?',
    sampleAudioUrl: '/audio/voice-previews/sarvam_shreya.mp3',
    provider: 'sarvam',
    languageCode: 'en-IN',
    gender: 'female',
    accent: 'Indian English',
    toneTags: ['Expressive', 'Dynamic'],
    characterArchetype: 'Performer',
    paletteKey: 'emerald',
  },
  {
    id: 'sarvam_shubh',
    name: 'Shubh (Sarvam)',
    description: 'Indian English / Indian languages via Sarvam (requires Intelligence SARVAM_API_KEY)',
    sampleText: 'Sudar is designed to learn with you, for you, every time you come back to study.',
    sampleAudioUrl: '/audio/voice-previews/sarvam_shubh.mp3',
    provider: 'sarvam',
    languageCode: 'en-IN',
    gender: 'male',
    accent: 'Indian English',
    toneTags: ['Conversational', 'Relaxed'],
    characterArchetype: 'Friend',
    paletteKey: 'violet',
  },
  {
    id: 'en-AU-NatashaNeural',
    name: 'Natasha (Australia)',
    description: 'Australian English, female',
    sampleText: 'Sudar helps you learn faster by adapting lessons to how you engage.',
    sampleAudioUrl: '/audio/voice-previews/en-AU-NatashaNeural.mp3',
    provider: 'edge',
    languageCode: 'en-AU',
    gender: 'female',
    accent: 'Australian English',
    toneTags: ['Bright', 'Clear'],
    characterArchetype: 'Facilitator',
    paletteKey: 'cyan',
  },
  {
    id: 'en-CA-ClaraNeural',
    name: 'Clara (Canada)',
    description: 'Canadian English, female',
    sampleText: 'Sudar keeps your learning journey personalized across every modality.',
    sampleAudioUrl: '/audio/voice-previews/en-CA-ClaraNeural.mp3',
    provider: 'edge',
    languageCode: 'en-CA',
    gender: 'female',
    accent: 'Canadian English',
    toneTags: ['Balanced', 'Friendly'],
    characterArchetype: 'Advisor',
    paletteKey: 'amber',
  },
  {
    id: 'hi-IN-SwaraNeural',
    name: 'Swara (Hindi)',
    description: 'Hindi, female',
    sampleText: 'Sudar aapke learning style ke hisaab se content ko personalize karta hai.',
    sampleAudioUrl: '/audio/voice-previews/hi-IN-SwaraNeural.mp3',
    provider: 'edge',
    languageCode: 'hi-IN',
    gender: 'female',
    accent: 'Hindi',
    toneTags: ['Warm', 'Assured'],
    characterArchetype: 'Teacher',
    paletteKey: 'rose',
  },
  {
    id: 'es-ES-ElviraNeural',
    name: 'Elvira (Spanish)',
    description: 'Spanish, female',
    sampleText: 'Sudar adapta cada curso para mejorar tu progreso de aprendizaje.',
    sampleAudioUrl: '/audio/voice-previews/es-ES-ElviraNeural.mp3',
    provider: 'edge',
    languageCode: 'es-ES',
    gender: 'female',
    accent: 'Spanish',
    toneTags: ['Energetic', 'Clear'],
    characterArchetype: 'Presenter',
    paletteKey: 'emerald',
  },
  {
    id: 'fr-FR-DeniseNeural',
    name: 'Denise (French)',
    description: 'French, female',
    sampleText: 'Sudar adapte vos cours selon votre rythme et vos preferences.',
    sampleAudioUrl: '/audio/voice-previews/fr-FR-DeniseNeural.mp3',
    provider: 'edge',
    languageCode: 'fr-FR',
    gender: 'female',
    accent: 'French',
    toneTags: ['Smooth', 'Poised'],
    characterArchetype: 'Narrator',
    paletteKey: 'violet',
  },
  {
    id: 'de-DE-KatjaNeural',
    name: 'Katja (German)',
    description: 'German, female',
    sampleText: 'Sudar passt Inhalte an, damit Lernen klarer und effektiver wird.',
    sampleAudioUrl: '/audio/voice-previews/de-DE-KatjaNeural.mp3',
    provider: 'edge',
    languageCode: 'de-DE',
    gender: 'female',
    accent: 'German',
    toneTags: ['Direct', 'Calm'],
    characterArchetype: 'Coach',
    paletteKey: 'cyan',
  },
  {
    id: 'ja-JP-NanamiNeural',
    name: 'Nanami (Japanese)',
    description: 'Japanese, female',
    sampleText: 'Sudar wa anata no manabikata ni awasete content o saitekika shimasu.',
    sampleAudioUrl: '/audio/voice-previews/ja-JP-NanamiNeural.mp3',
    provider: 'edge',
    languageCode: 'ja-JP',
    gender: 'female',
    accent: 'Japanese',
    toneTags: ['Gentle', 'Focused'],
    characterArchetype: 'Guide',
    paletteKey: 'amber',
  },
  {
    id: 'pt-BR-FranciscaNeural',
    name: 'Francisca (Brazil)',
    description: 'Portuguese (Brazil), female',
    sampleText: 'Sudar personaliza suas aulas para acelerar seu aprendizado.',
    sampleAudioUrl: '/audio/voice-previews/pt-BR-FranciscaNeural.mp3',
    provider: 'edge',
    languageCode: 'pt-BR',
    gender: 'female',
    accent: 'Brazilian Portuguese',
    toneTags: ['Friendly', 'Confident'],
    characterArchetype: 'Mentor',
    paletteKey: 'rose',
  },
  {
    id: 'ar-SA-ZariyahNeural',
    name: 'Zariyah (Arabic)',
    description: 'Arabic (Saudi Arabia), female',
    sampleText: 'Sudar يساعدك على التعلم بطريقتك.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'ar-SA',
    gender: 'female',
    accent: 'Arabic',
    toneTags: ['Clear', 'Warm'],
    characterArchetype: 'Guide',
    paletteKey: 'violet',
  },
  {
    id: 'zh-CN-XiaoxiaoNeural',
    name: 'Xiaoxiao (Chinese)',
    description: 'Chinese (Simplified), female',
    sampleText: 'Sudar 会根据你的学习方式调整内容。',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'zh-CN',
    gender: 'female',
    accent: 'Mandarin (Simplified)',
    toneTags: ['Friendly', 'Clear'],
    characterArchetype: 'Mentor',
    paletteKey: 'cyan',
  },
  {
    id: 'zh-TW-HsiaoChenNeural',
    name: 'Hsiao Chen (Chinese)',
    description: 'Chinese (Traditional), female',
    sampleText: 'Sudar 讓學習更貼近你的節奏。',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'zh-TW',
    gender: 'female',
    accent: 'Mandarin (Traditional)',
    toneTags: ['Calm', 'Supportive'],
    characterArchetype: 'Guide',
    paletteKey: 'amber',
  },
  {
    id: 'ko-KR-SunHiNeural',
    name: 'Sun-Hi (Korean)',
    description: 'Korean, female',
    sampleText: 'Sudar는 당신의 학습 스타일에 맞춥니다.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'ko-KR',
    gender: 'female',
    accent: 'Korean',
    toneTags: ['Bright', 'Focused'],
    characterArchetype: 'Coach',
    paletteKey: 'rose',
  },
  {
    id: 'ru-RU-SvetlanaNeural',
    name: 'Svetlana (Russian)',
    description: 'Russian, female',
    sampleText: 'Sudar подстраивает курсы под ваш темп.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'ru-RU',
    gender: 'female',
    accent: 'Russian',
    toneTags: ['Clear', 'Steady'],
    characterArchetype: 'Presenter',
    paletteKey: 'violet',
  },
  {
    id: 'it-IT-ElsaNeural',
    name: 'Elsa (Italian)',
    description: 'Italian, female',
    sampleText: 'Sudar adatta i corsi al tuo modo di studiare.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'it-IT',
    gender: 'female',
    accent: 'Italian',
    toneTags: ['Warm', 'Expressive'],
    characterArchetype: 'Host',
    paletteKey: 'emerald',
  },
  {
    id: 'nl-NL-FennaNeural',
    name: 'Fenna (Dutch)',
    description: 'Dutch, female',
    sampleText: 'Sudar past lessen aan op jouw tempo.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'nl-NL',
    gender: 'female',
    accent: 'Dutch',
    toneTags: ['Friendly', 'Clear'],
    characterArchetype: 'Guide',
    paletteKey: 'cyan',
  },
  {
    id: 'pl-PL-AgnieszkaNeural',
    name: 'Agnieszka (Polish)',
    description: 'Polish, female',
    sampleText: 'Sudar dopasowuje kursy do Twojego stylu nauki.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'pl-PL',
    gender: 'female',
    accent: 'Polish',
    toneTags: ['Direct', 'Supportive'],
    characterArchetype: 'Coach',
    paletteKey: 'amber',
  },
  {
    id: 'tr-TR-EmelNeural',
    name: 'Emel (Turkish)',
    description: 'Turkish, female',
    sampleText: 'Sudar dersleri senin tempona göre uyarlar.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'tr-TR',
    gender: 'female',
    accent: 'Turkish',
    toneTags: ['Warm', 'Clear'],
    characterArchetype: 'Mentor',
    paletteKey: 'rose',
  },
  {
    id: 'id-ID-GadisNeural',
    name: 'Gadis (Indonesian)',
    description: 'Indonesian, female',
    sampleText: 'Sudar menyesuaikan pembelajaran dengan gayamu.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'id-ID',
    gender: 'female',
    accent: 'Indonesian',
    toneTags: ['Friendly', 'Bright'],
    characterArchetype: 'Guide',
    paletteKey: 'violet',
  },
  {
    id: 'vi-VN-HoaiMyNeural',
    name: 'Hoai My (Vietnamese)',
    description: 'Vietnamese, female',
    sampleText: 'Sudar điều chỉnh nội dung theo cách bạn học.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'vi-VN',
    gender: 'female',
    accent: 'Vietnamese',
    toneTags: ['Clear', 'Gentle'],
    characterArchetype: 'Teacher',
    paletteKey: 'cyan',
  },
  {
    id: 'bn-BD-NabanitaNeural',
    name: 'Nabanita (Bengali)',
    description: 'Bengali, female',
    sampleText: 'Sudar আপনার শেখার ধরন অনুযায়ী কন্টেন্ট মানিয়ে নেয়।',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'bn-BD',
    gender: 'female',
    accent: 'Bengali',
    toneTags: ['Warm', 'Assured'],
    characterArchetype: 'Teacher',
    paletteKey: 'rose',
  },
  {
    id: 'ta-IN-PallaviNeural',
    name: 'Pallavi (Tamil)',
    description: 'Tamil, female',
    sampleText: 'Sudar உங்கள் கற்றலுக்கு ஏற்ப உள்ளடக்கத்தை மாற்றும்.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'ta-IN',
    gender: 'female',
    accent: 'Tamil',
    toneTags: ['Clear', 'Supportive'],
    characterArchetype: 'Guide',
    paletteKey: 'emerald',
  },
  {
    id: 'te-IN-ShrutiNeural',
    name: 'Shruti (Telugu)',
    description: 'Telugu, female',
    sampleText: 'Sudar మీ నేర్చుకునే విధానానికి అనుగుణంగా కంటెంట్‌ను సరిచేస్తుంది.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'te-IN',
    gender: 'female',
    accent: 'Telugu',
    toneTags: ['Warm', 'Clear'],
    characterArchetype: 'Mentor',
    paletteKey: 'amber',
  },
  {
    id: 'ur-PK-UzmaNeural',
    name: 'Uzma (Urdu)',
    description: 'Urdu, female',
    sampleText: 'Sudar آپ کے اندازِ سیکھنے کے مطابق مواد ڈھالتا ہے۔',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'ur-PK',
    gender: 'female',
    accent: 'Urdu',
    toneTags: ['Calm', 'Clear'],
    characterArchetype: 'Guide',
    paletteKey: 'violet',
  },
  {
    id: 'fa-IR-DilaraNeural',
    name: 'Dilara (Persian)',
    description: 'Persian, female',
    sampleText: 'Sudar محتوا را با سبک یادگیری شما هماهنگ می‌کند.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'fa-IR',
    gender: 'female',
    accent: 'Persian',
    toneTags: ['Smooth', 'Supportive'],
    characterArchetype: 'Narrator',
    paletteKey: 'cyan',
  },
  {
    id: 'he-IL-HilaNeural',
    name: 'Hila (Hebrew)',
    description: 'Hebrew, female',
    sampleText: 'Sudar מתאים את התוכן לאופן הלמידה שלך.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'he-IL',
    gender: 'female',
    accent: 'Hebrew',
    toneTags: ['Clear', 'Warm'],
    characterArchetype: 'Teacher',
    paletteKey: 'rose',
  },
  {
    id: 'sw-KE-ZuriNeural',
    name: 'Zuri (Swahili)',
    description: 'Swahili, female',
    sampleText: 'Sudar inabadilisha maudhui kwa kuzingatia jinsi unavyojifunza.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'sw-KE',
    gender: 'female',
    accent: 'Swahili',
    toneTags: ['Bright', 'Friendly'],
    characterArchetype: 'Guide',
    paletteKey: 'emerald',
  },
  {
    id: 'uk-UA-PolinaNeural',
    name: 'Polina (Ukrainian)',
    description: 'Ukrainian, female',
    sampleText: 'Sudar підлаштовує курси під ваш темп навчання.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'uk-UA',
    gender: 'female',
    accent: 'Ukrainian',
    toneTags: ['Clear', 'Steady'],
    characterArchetype: 'Coach',
    paletteKey: 'violet',
  },
  {
    id: 'ms-MY-YasminNeural',
    name: 'Yasmin (Malay)',
    description: 'Malay, female',
    sampleText: 'Sudar menyesuaikan kandungan dengan cara anda belajar.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'ms-MY',
    gender: 'female',
    accent: 'Malay',
    toneTags: ['Warm', 'Clear'],
    characterArchetype: 'Mentor',
    paletteKey: 'amber',
  },
  {
    id: 'th-TH-PremwadeeNeural',
    name: 'Premwadee (Thai)',
    description: 'Thai, female',
    sampleText: 'Sudar ปรับเนื้อหาให้เข้ากับสไตล์การเรียนของคุณ',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'th-TH',
    gender: 'female',
    accent: 'Thai',
    toneTags: ['Friendly', 'Clear'],
    characterArchetype: 'Guide',
    paletteKey: 'cyan',
  },
  {
    id: 'gu-IN-DhwaniNeural',
    name: 'Dhwani (Gujarati)',
    description: 'Gujarati, female',
    sampleText: 'Sudar તમારા શીખવાની શૈલી અનુસાર સામગ્રી ગોઠવે છે.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'gu-IN',
    gender: 'female',
    accent: 'Gujarati',
    toneTags: ['Warm', 'Assured'],
    characterArchetype: 'Teacher',
    paletteKey: 'rose',
  },
  {
    id: 'pa-IN-VaaniNeural',
    name: 'Vaani (Punjabi)',
    description: 'Punjabi, female',
    sampleText: 'Sudar ਤੁਹਾਡੇ ਸਿੱਖਣ ਦੇ ਢੰਗ ਅਨੁਸਾਰ ਸਮੱਗਰੀ ਢਾਲਦਾ ਹੈ।',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'pa-IN',
    gender: 'female',
    accent: 'Punjabi',
    toneTags: ['Bright', 'Clear'],
    characterArchetype: 'Presenter',
    paletteKey: 'emerald',
  },
  {
    id: 'ne-NP-HemkalaNeural',
    name: 'Hemkala (Nepali)',
    description: 'Nepali, female',
    sampleText: 'Sudar तपाईंको सिकाइ शैली अनुसार सामग्री मिलाउँछ।',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'ne-NP',
    gender: 'female',
    accent: 'Nepali',
    toneTags: ['Warm', 'Supportive'],
    characterArchetype: 'Guide',
    paletteKey: 'violet',
  },
  {
    id: 'mr-IN-AarohiNeural',
    name: 'Aarohi (Marathi)',
    description: 'Marathi, female',
    sampleText: 'Sudar तुमच्या शिकण्याच्या पद्धतीनुसार सामग्री जुळवते.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'mr-IN',
    gender: 'female',
    accent: 'Marathi',
    toneTags: ['Clear', 'Warm'],
    characterArchetype: 'Teacher',
    paletteKey: 'cyan',
  },
  {
    id: 'kn-IN-SapnaNeural',
    name: 'Sapna (Kannada)',
    description: 'Kannada, female',
    sampleText: 'Sudar ನಿಮ್ಮ ಕಲಿಕೆಯ ಶೈಲಿಗೆ ಅನುಗುಣವಾಗಿ ವಿಷಯವನ್ನು ಹೊಂದಿಸುತ್ತದೆ.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'kn-IN',
    gender: 'female',
    accent: 'Kannada',
    toneTags: ['Friendly', 'Focused'],
    characterArchetype: 'Mentor',
    paletteKey: 'amber',
  },
  {
    id: 'es-MX-DaliaNeural',
    name: 'Dalia (Spanish Mexico)',
    description: 'Spanish (Mexico), female',
    sampleText: 'Sudar adapta el contenido a tu forma de aprender.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'es-MX',
    gender: 'female',
    accent: 'Latin American Spanish',
    toneTags: ['Warm', 'Clear'],
    characterArchetype: 'Host',
    paletteKey: 'rose',
  },
  {
    id: 'fr-CA-SylvieNeural',
    name: 'Sylvie (French Canada)',
    description: 'French (Canada), female',
    sampleText: 'Sudar adapte le contenu à votre façon d’apprendre.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'fr-CA',
    gender: 'female',
    accent: 'Canadian French',
    toneTags: ['Friendly', 'Clear'],
    characterArchetype: 'Guide',
    paletteKey: 'violet',
  },
  {
    id: 'pt-PT-RaquelNeural',
    name: 'Raquel (Portuguese Portugal)',
    description: 'Portuguese (Portugal), female',
    sampleText: 'Sudar adapta o conteúdo ao teu estilo de aprendizagem.',
    sampleAudioUrl: '/audio/voice-previews/en-US-JennyNeural.mp3',
    provider: 'edge',
    languageCode: 'pt-PT',
    gender: 'female',
    accent: 'European Portuguese',
    toneTags: ['Clear', 'Poised'],
    characterArchetype: 'Presenter',
    paletteKey: 'cyan',
  },
]

export const TTS_VOICE_OPTIONS_BY_ID = Object.fromEntries(
  TTS_VOICE_OPTIONS.map((voice) => [voice.id, voice])
) as Record<string, TtsVoiceOption>

export const TTS_VOICE_ID_ALIASES: Record<string, string> = {
  /** Legacy ids from older builds — map to stable Edge neural voices. */
  india_shreya: 'en-IN-NeerjaNeural',
  india_shubh: 'en-IN-PrabhatNeural',
}

export function normalizeTtsVoiceId(voiceId: string | null | undefined): string | null {
  if (!voiceId) return null
  return TTS_VOICE_ID_ALIASES[voiceId] ?? voiceId
}
